version: '3.7'

services:

  db:
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: example
      MARIADB_USER: example
      MARIADB_PASSWORD: secret
    container_name: laravel-ddd-example.db
    image: mariadb:10.7.4
    ports:
      - "3360:3306"
    restart: unless-stopped
    volumes:
      - laravel-ddd-example.dbdata:/var/lib/mysql/
    networks:
      - laravel-ddd-example

  app:
    build:
      context: ./../../
      dockerfile: ./etc/docker/php.Dockerfile
    container_name: laravel-ddd-example.app
    command: php -S laravel-ddd-example.app:8080 -t ./apps/kanban-api/public
    restart: unless-stopped
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - ./../../:/var/www
    depends_on:
      - db
    networks:
      - laravel-ddd-example

  adminer:
    image: adminer
    container_name: laravel-ddd-example.adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8081:8080"
    networks:
      - laravel-ddd-example

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: laravel-ddd-example.rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - laravel-ddd-example

networks:
  laravel-ddd-example:
    driver: bridge

volumes:
  laravel-ddd-example.dbdata:
    driver: local
